// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "QuakeSense",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "QuakeSense",
            targets: ["AppModule"],
            bundleIdentifier: "com.will702.QuakeSense",
            teamIdentifier: "48FS3GMUGV",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Marketing", "scripts"],
            resources: [.process("Sounds")]
        )
    ],
    swiftLanguageVersions: [.v6]
)
